// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.44.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for CompositionTestAPIVersion.
const (
	CompositionTestAPIVersionmetaDevUpboundIoV1Alpha1 CompositionTestAPIVersion = "meta.dev.upbound.io/v1alpha1"
)

// Defines values for CompositionTestKind.
const (
	CompositionTestKindCompositionTest CompositionTestKind = "CompositionTest"
)

// IoUpboundDevMetaV1Alpha1CompositionTest CompositionTest defines the schema for the CompositionTest custom resource.
type IoUpboundDevMetaV1Alpha1CompositionTest = CompositionTest

// CompositionTestAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type CompositionTestAPIVersion string

// CompositionTestKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type CompositionTestKind string

// CompositionTestSpecAssertResourcesItem defines model for .
type CompositionTestSpecAssertResourcesItem = map[string]interface{}

// CompositionTestSpecComposition Composition specifies the composition definition inline.
// Optional.
type CompositionTestSpecComposition = map[string]interface{}

// CompositionTestSpecExtraResourcesItem defines model for .
type CompositionTestSpecExtraResourcesItem = map[string]interface{}

// CompositionTestSpecObservedResourcesItem defines model for .
type CompositionTestSpecObservedResourcesItem = map[string]interface{}

// CompositionTestSpecXr XR specifies the composite resource (XR) inline.
// Mutually exclusive with XRPath. At least one of XR or XRPath must be specified.
type CompositionTestSpecXr = map[string]interface{}

// CompositionTestSpecXrd XRD specifies the XRD definition inline.
// Optional.
type CompositionTestSpecXrd = map[string]interface{}

// CompositionTestSpec CompositionTestSpec defines the specification for the CompositionTest custom resource.
type CompositionTestSpec struct {
	// AssertResources AssertResources defines assertions to validate resources after test completion.
	// Optional.
	AssertResources *[]CompositionTestSpecAssertResourcesItem `json:"assertResources,omitempty"`

	// Composition Composition specifies the composition definition inline.
	// Optional.
	Composition *CompositionTestSpecComposition `json:"composition,omitempty"`

	// CompositionPath Composition specifies the composition definition path.
	// Optional.
	CompositionPath *string `json:"compositionPath,omitempty"`

	// Context Context specifies context for the Function Pipeline inline as key-value pairs.
	// Keys are context keys, values are JSON data.
	// Optional.
	Context *map[string]map[string]interface{} `json:"context,omitempty"`

	// ExtraResources ExtraResources specifies additional resources inline.
	// Optional.
	ExtraResources *[]CompositionTestSpecExtraResourcesItem `json:"extraResources,omitempty"`

	// FunctionCredentialsPath FunctionCredentialsPath specifies a path to a credentials file to be passed to tests.
	// Optional.
	FunctionCredentialsPath *string `json:"functionCredentialsPath,omitempty"`

	// ObservedResources ObservedResources specifies additional observed resources inline.
	// Optional.
	ObservedResources *[]CompositionTestSpecObservedResourcesItem `json:"observedResources,omitempty"`

	// TimeoutSeconds Timeout for the test in seconds
	// Required. Default is 30s.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`

	// Validate Validate indicates whether to validate managed resources against schemas.
	// Optional.
	Validate *bool `json:"validate,omitempty"`

	// Xr XR specifies the composite resource (XR) inline.
	// Mutually exclusive with XRPath. At least one of XR or XRPath must be specified.
	Xr *CompositionTestSpecXr `json:"xr,omitempty"`

	// XrPath XRPath specifies the composite resource (XR) path.
	// Mutually exclusive with XR. At least one of XR or XRPath must be specified.
	XrPath *string `json:"xrPath,omitempty"`

	// Xrd XRD specifies the XRD definition inline.
	// Optional.
	Xrd *CompositionTestSpecXrd `json:"xrd,omitempty"`

	// XrdPath XRD specifies the XRD definition path.
	// Optional.
	XrdPath *string `json:"xrdPath,omitempty"`
}

// CompositionTest CompositionTest defines the schema for the CompositionTest custom resource.
type CompositionTest struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *CompositionTestAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *CompositionTestKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec CompositionTestSpec defines the specification for the CompositionTest custom resource.
	Spec *CompositionTestSpec `json:"spec,omitempty"`
}

// IoUpboundDevMetaV1Alpha1CompositionTestList CompositionTestList is a list of CompositionTest
type IoUpboundDevMetaV1Alpha1CompositionTestList = CompositionTestList

// CompositionTestList CompositionTestList is a list of CompositionTest
type CompositionTestList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of compositiontests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundDevMetaV1Alpha1CompositionTest `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
