// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.44.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for E2ETestAPIVersion.
const (
	E2ETestAPIVersionmetaDevUpboundIoV1Alpha1 E2ETestAPIVersion = "meta.dev.upbound.io/v1alpha1"
)

// Defines values for E2ETestKind.
const (
	E2ETestKindE2ETest E2ETestKind = "E2ETest"
)

// Defines values for E2ETestSpecCrossplaneAutoUpgradeChannel.
const (
	E2ETestSpecCrossplaneAutoUpgradeChannelNone   E2ETestSpecCrossplaneAutoUpgradeChannel = "None"
	E2ETestSpecCrossplaneAutoUpgradeChannelPatch  E2ETestSpecCrossplaneAutoUpgradeChannel = "Patch"
	E2ETestSpecCrossplaneAutoUpgradeChannelRapid  E2ETestSpecCrossplaneAutoUpgradeChannel = "Rapid"
	E2ETestSpecCrossplaneAutoUpgradeChannelStable E2ETestSpecCrossplaneAutoUpgradeChannel = "Stable"
)

// Defines values for E2ETestSpecCrossplaneState.
const (
	E2ETestSpecCrossplaneStatePaused  E2ETestSpecCrossplaneState = "Paused"
	E2ETestSpecCrossplaneStateRunning E2ETestSpecCrossplaneState = "Running"
)

// IoUpboundDevMetaV1Alpha1E2ETest E2ETest defines the schema for the E2ETest custom resource used for e2e
// testing of Crossplane configurations in controlplanes.
type IoUpboundDevMetaV1Alpha1E2ETest = E2ETest

// E2ETestAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type E2ETestAPIVersion string

// E2ETestKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type E2ETestKind string

// E2ETestSpecCrossplaneAutoUpgradeChannel Channel defines the upgrade channels for Crossplane. We support the following channels where 'Stable' is the
// default:
//   - None: disables auto-upgrades and keeps the control plane at its current version of Crossplane.
//   - Patch: automatically upgrades the control plane to the latest supported patch version when it
//     becomes available while keeping the minor version the same.
//   - Stable: automatically upgrades the control plane to the latest supported patch release on minor
//     version N-1, where N is the latest supported minor version.
//   - Rapid: automatically upgrades the cluster to the latest supported patch release on the latest
//     supported minor version.
type E2ETestSpecCrossplaneAutoUpgradeChannel string

// E2ETestSpecCrossplaneAutoUpgrade AutoUpgrades defines the auto upgrade configuration for Crossplane.
type E2ETestSpecCrossplaneAutoUpgrade struct {
	// Channel Channel defines the upgrade channels for Crossplane. We support the following channels where 'Stable' is the
	// default:
	// - None: disables auto-upgrades and keeps the control plane at its current version of Crossplane.
	// - Patch: automatically upgrades the control plane to the latest supported patch version when it
	//   becomes available while keeping the minor version the same.
	// - Stable: automatically upgrades the control plane to the latest supported patch release on minor
	//   version N-1, where N is the latest supported minor version.
	// - Rapid: automatically upgrades the cluster to the latest supported patch release on the latest
	//   supported minor version.
	Channel *E2ETestSpecCrossplaneAutoUpgradeChannel `json:"channel,omitempty"`
}

// E2ETestSpecCrossplaneState State defines the state for crossplane and provider workloads. We support
// the following states where 'Running' is the default:
// - Running: Starts/Scales up all crossplane and provider workloads in the ControlPlane
// - Paused: Pauses/Scales down all crossplane and provider workloads in the ControlPlane
type E2ETestSpecCrossplaneState string

// E2ETestSpecCrossplane Crossplane specifies the Crossplane configuration and settings required
// for this test. This includes the version of Universal Crossplane to
// install, and optional auto-upgrade settings. The configuration defined
// here will be used to set up the controlplane before applying the test
// manifests.
type E2ETestSpecCrossplane struct {
	// AutoUpgrade AutoUpgrades defines the auto upgrade configuration for Crossplane.
	AutoUpgrade *E2ETestSpecCrossplaneAutoUpgrade `json:"autoUpgrade,omitempty"`

	// State State defines the state for crossplane and provider workloads. We support
	// the following states where 'Running' is the default:
	// - Running: Starts/Scales up all crossplane and provider workloads in the ControlPlane
	// - Paused: Pauses/Scales down all crossplane and provider workloads in the ControlPlane
	State *E2ETestSpecCrossplaneState `json:"state,omitempty"`

	// Version Version is the version of Universal Crossplane to install.
	Version *string `json:"version,omitempty"`
}

// E2ETestSpecExtraResourcesItem defines model for .
type E2ETestSpecExtraResourcesItem = map[string]interface{}

// E2ETestSpecInitResourcesItem defines model for .
type E2ETestSpecInitResourcesItem = map[string]interface{}

// E2ETestSpecManifestsItem defines model for .
type E2ETestSpecManifestsItem = map[string]interface{}

// E2ETestSpec E2ETestSpec defines the specification for e2e testing of Crossplane
// configurations. It orchestrates the complete test lifecycle including setting
// up controlplane, applying test resources in the correct order (InitResources
// → Configuration → ExtraResources → Manifests), validating conditions, and
// handling cleanup. This spec allows you to define e2e tests that verify your
// Crossplane compositions, providers, and managed resources work correctly
// together in a real controlplane environment.
type E2ETestSpec struct {
	// CleanupTimeoutSeconds CleanupTimeoutSeconds defines the maximum duration in seconds for cleanup
	// operations after the test completes. This timeout applies to the deletion
	// of test resources and any associated managed resources. If not specified,
	// defaults to 600 seconds (10 minutes). Consider increasing this value for
	// tests with many resources or complex deletion dependencies.
	CleanupTimeoutSeconds *int `json:"cleanupTimeoutSeconds,omitempty"`

	// Crossplane Crossplane specifies the Crossplane configuration and settings required
	// for this test. This includes the version of Universal Crossplane to
	// install, and optional auto-upgrade settings. The configuration defined
	// here will be used to set up the controlplane before applying the test
	// manifests.
	Crossplane *E2ETestSpecCrossplane `json:"crossplane,omitempty"`

	// DefaultConditions DefaultConditions specifies the expected conditions that should be met
	// after the manifests are applied. These are validation checks that verify
	// the resources are functioning correctly. Each condition is a string
	// expression that will be evaluated against the deployed resources. Common
	// conditions include checking resource status for readiness
	DefaultConditions *[]string `json:"defaultConditions,omitempty"`

	// ExtraResources ExtraResources specifies additional Kubernetes resources that should be
	// created or updated after the configuration has been successfully applied.
	// These resources may depend on the primary configuration being in place.
	// Common use cases include ConfigMaps, Secrets, providerConfigs. Each
	// resource must be a valid Kubernetes object.
	ExtraResources *[]E2ETestSpecExtraResourcesItem `json:"extraResources,omitempty"`

	// InitResources InitResources specifies Kubernetes resources that must be created or
	// updated before the configuration is applied. These are typically
	// prerequisite resources that the configuration depends on. Common use
	// cases include ImageConfigs, DeploymentRuntimeConfigs, or any foundational
	// resources required for the configuration to work. Each resource must be a
	// valid Kubernetes object.
	InitResources *[]E2ETestSpecInitResourcesItem `json:"initResources,omitempty"`

	// Manifests Manifests contains the Kubernetes resources that will be applied as part
	// of this e2e test. These are the primary resources being tested - they
	// will be created in the controlplane and then validated against the
	// conditions specified in DefaultConditions. Each manifest must be a valid
	// Kubernetes object. At least one manifest is required. Examples include
	// Claims, Composite Resources or any Kubernetes resource you want to test.
	Manifests *[]E2ETestSpecManifestsItem `json:"manifests,omitempty"`

	// SkipDelete If true, skip resource deletion after test
	SkipDelete *bool `json:"skipDelete,omitempty"`

	// TimeoutSeconds TimeoutSeconds defines the maximum duration in seconds that the test is
	// allowed to run before being marked as failed. This includes time for
	// resource creation, condition checks, and any reconciliation processes. If
	// not specified, a default timeout will be used. Consider setting higher
	// values for tests involving complex resources or those requiring multiple
	// reconciliation cycles.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// E2ETest E2ETest defines the schema for the E2ETest custom resource used for e2e
// testing of Crossplane configurations in controlplanes.
type E2ETest struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *E2ETestAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *E2ETestKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec E2ETestSpec defines the specification for e2e testing of Crossplane
	// configurations. It orchestrates the complete test lifecycle including setting
	// up controlplane, applying test resources in the correct order (InitResources
	// → Configuration → ExtraResources → Manifests), validating conditions, and
	// handling cleanup. This spec allows you to define e2e tests that verify your
	// Crossplane compositions, providers, and managed resources work correctly
	// together in a real controlplane environment.
	Spec *E2ETestSpec `json:"spec,omitempty"`
}

// IoUpboundDevMetaV1Alpha1E2ETestList E2ETestList is a list of E2ETest
type IoUpboundDevMetaV1Alpha1E2ETestList = E2ETestList

// E2ETestList E2ETestList is a list of E2ETest
type E2ETestList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of e2etests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundDevMetaV1Alpha1E2ETest `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
