// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.44.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for OperationTestAPIVersion.
const (
	OperationTestAPIVersionmetaDevUpboundIoV1Alpha1 OperationTestAPIVersion = "meta.dev.upbound.io/v1alpha1"
)

// Defines values for OperationTestKind.
const (
	OperationTestKindOperationTest OperationTestKind = "OperationTest"
)

// IoUpboundDevMetaV1Alpha1OperationTest OperationTest defines the schema for the OperationTest custom resource.
type IoUpboundDevMetaV1Alpha1OperationTest = OperationTest

// OperationTestAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type OperationTestAPIVersion string

// OperationTestKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type OperationTestKind string

// OperationTestSpecAssertResourcesItem defines model for .
type OperationTestSpecAssertResourcesItem = map[string]interface{}

// OperationTestSpecOperation Operation specifies the Operation definition inline.
// Optional.
type OperationTestSpecOperation = map[string]interface{}

// OperationTestSpecRequiredResourcesItem defines model for .
type OperationTestSpecRequiredResourcesItem = map[string]interface{}

// OperationTestSpec OperationTestSpec defines the specification for the OperationTest custom resource.
type OperationTestSpec struct {
	// AssertResources AssertResources defines assertions to validate resources after test completion.
	// Optional.
	AssertResources *[]OperationTestSpecAssertResourcesItem `json:"assertResources,omitempty"`

	// Context Context specifies context for the Function Pipeline inline as key-value pairs.
	// Keys are context keys, values are JSON data.
	// Optional.
	Context *map[string]map[string]interface{} `json:"context,omitempty"`

	// FunctionCredentialsPath FunctionCredentialsPath specifies a path to a credentials file to be passed to tests.
	// Optional.
	FunctionCredentialsPath *string `json:"functionCredentialsPath,omitempty"`

	// Operation Operation specifies the Operation definition inline.
	// Optional.
	Operation *OperationTestSpecOperation `json:"operation,omitempty"`

	// OperationPath OperationPath specifies the XRD definition path.
	// Optional.
	OperationPath *string `json:"operationPath,omitempty"`

	// RequiredResources RequiredResources specifies additional required resources inline.
	// Optional.
	RequiredResources *[]OperationTestSpecRequiredResourcesItem `json:"requiredResources,omitempty"`

	// RequiredResourcesPath RequiredResourcesPath specifies a path to required resources file.
	// Optional.
	RequiredResourcesPath *string `json:"requiredResourcesPath,omitempty"`

	// TimeoutSeconds Timeout for the test in seconds
	// Required. Default is 30s.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// OperationTest OperationTest defines the schema for the OperationTest custom resource.
type OperationTest struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *OperationTestAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *OperationTestKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec OperationTestSpec defines the specification for the OperationTest custom resource.
	Spec *OperationTestSpec `json:"spec,omitempty"`
}

// IoUpboundDevMetaV1Alpha1OperationTestList OperationTestList is a list of OperationTest
type IoUpboundDevMetaV1Alpha1OperationTestList = OperationTestList

// OperationTestList OperationTestList is a list of OperationTest
type OperationTestList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of operationtests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundDevMetaV1Alpha1OperationTest `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
