// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.44.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for ProjectAPIVersion.
const (
	ProjectAPIVersionmetaDevUpboundIoV1Alpha1 ProjectAPIVersion = "meta.dev.upbound.io/v1alpha1"
)

// Defines values for ProjectKind.
const (
	ProjectKindProject ProjectKind = "Project"
)

// Defines values for ProjectSpecAPIDependenciesItemType.
const (
	ProjectSpecAPIDependenciesItemTypecrd ProjectSpecAPIDependenciesItemType = "crd"
	ProjectSpecAPIDependenciesItemTypek8S ProjectSpecAPIDependenciesItemType = "k8s"
)

// Defines values for ProjectSpecImageConfigItemMatchImagesItemType.
const (
	ProjectSpecImageConfigItemMatchImagesItemTypePrefix ProjectSpecImageConfigItemMatchImagesItemType = "Prefix"
)

// IoUpboundDevMetaV1Alpha1Project Project defines an Upbound Project, which can be built into a Crossplane
// Configuration.
type IoUpboundDevMetaV1Alpha1Project = Project

// ProjectAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ProjectAPIVersion string

// ProjectKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ProjectKind string

// ProjectSpecAPIDependenciesItemGit Git defines the git repository source for the API dependency.
type ProjectSpecAPIDependenciesItemGit struct {
	// Path Path is the path within the repository to the API definition.
	Path *string `json:"path,omitempty"`

	// Ref Ref is the git reference (branch, tag, or commit SHA).
	Ref *string `json:"ref,omitempty"`

	// Repository Repository is the git repository URL.
	Repository *string `json:"repository,omitempty"`
}

// ProjectSpecAPIDependenciesItemHTTP HTTP defines the HTTP source for the API dependency.
type ProjectSpecAPIDependenciesItemHTTP struct {
	// URL URL is the HTTP/HTTPS URL to fetch the API dependency from.
	URL *string `json:"url,omitempty"`
}

// ProjectSpecAPIDependenciesItemK8S K8s defines the Kubernetes API version for the dependency.
type ProjectSpecAPIDependenciesItemK8S struct {
	// Version Version is the Kubernetes API version (e.g., "v1.33.0").
	Version *string `json:"version,omitempty"`
}

// ProjectSpecAPIDependenciesItemType Type defines the type of API dependency.
type ProjectSpecAPIDependenciesItemType string

// ProjectSpecAPIDependenciesItem APIDependencies defines a reference to an external API dependency.
// NOTE: This is an experimental feature and is subject to change.
type ProjectSpecAPIDependenciesItem struct {
	// Git Git defines the git repository source for the API dependency.
	Git *ProjectSpecAPIDependenciesItemGit `json:"git,omitempty"`

	// HTTP HTTP defines the HTTP source for the API dependency.
	HTTP *ProjectSpecAPIDependenciesItemHTTP `json:"http,omitempty"`

	// K8S K8s defines the Kubernetes API version for the dependency.
	K8S *ProjectSpecAPIDependenciesItemK8S `json:"k8s,omitempty"`

	// Type Type defines the type of API dependency.
	Type *ProjectSpecAPIDependenciesItemType `json:"type,omitempty"`
}

// ProjectSpecCrossplane CrossplaneConstraints specifies a packages compatibility with Crossplane versions.
type ProjectSpecCrossplane struct {
	// Version Semantic version constraints of Crossplane that package is compatible with.
	Version *string `json:"version,omitempty"`
}

// ProjectSpecDependsOnItem Dependency is a dependency on another package. A dependency can be of an
// arbitrary API version and kind, but Crossplane expects package dependencies
// to behave like a Crossplane package. Specifically it expects to be able to
// create the dependency and set its spec.package field to a package OCI
// reference.
type ProjectSpecDependsOnItem struct {
	// APIVersion APIVersion of the dependency.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Configuration Configuration is the name of a Configuration package image.
	// Must be a fully qualified image name, including the registry,
	// Deprecated: Specify an apiVersion, kind, and package instead.
	Configuration *string `json:"configuration,omitempty"`

	// Function Function is the name of a Function package image.
	// Must be a fully qualified image name, including the registry,
	// Deprecated: Specify an apiVersion, kind, and package instead.
	Function *string `json:"function,omitempty"`

	// Kind Kind of the dependency.
	Kind *string `json:"kind,omitempty"`

	// Package Package OCI reference of the dependency. Only used when apiVersion and
	// kind are set.
	// Must be a fully qualified image name, including the registry,
	// repository, and tag. For example, "registry.example.com/repo/package:tag".
	Package *string `json:"package,omitempty"`

	// Provider Provider is the name of a Provider package image.
	// Must be a fully qualified image name, including the registry,
	// Deprecated: Specify an apiVersion and kind instead.
	Provider *string `json:"provider,omitempty"`

	// Version Version is the semantic version constraints of the dependency image.
	Version *string `json:"version,omitempty"`
}

// ProjectSpecImageConfigItemMatchImagesItemType Type is the type of match.
type ProjectSpecImageConfigItemMatchImagesItemType string

// ProjectSpecImageConfigItemMatchImagesItem ImageMatch defines a rule for matching image.
type ProjectSpecImageConfigItemMatchImagesItem struct {
	// Prefix Prefix is the prefix that should be matched.
	Prefix *string `json:"prefix,omitempty"`

	// Type Type is the type of match.
	Type *ProjectSpecImageConfigItemMatchImagesItemType `json:"type,omitempty"`
}

// ProjectSpecImageConfigItemRewriteImage RewriteImage defines how a matched image should be rewritten.
type ProjectSpecImageConfigItemRewriteImage struct {
	// Prefix Prefix is the prefix to use when rewriting the image.
	Prefix *string `json:"prefix,omitempty"`
}

// ProjectSpecImageConfigItem ImageConfig defines a set of rules for matching and rewriting images.
type ProjectSpecImageConfigItem struct {
	// MatchImages MatchImages is a list of image matching rules that should be satisfied.
	MatchImages *[]ProjectSpecImageConfigItemMatchImagesItem `json:"matchImages,omitempty"`

	// RewriteImage RewriteImage defines how a matched image should be rewritten.
	RewriteImage *ProjectSpecImageConfigItemRewriteImage `json:"rewriteImage,omitempty"`
}

// ProjectSpecPaths ProjectPaths configures the locations of various parts of the project, for
// use at build time.
type ProjectSpecPaths struct {
	// Apis APIs is the directory holding the project's apis. If not
	// specified, it defaults to `apis/`.
	Apis *string `json:"apis,omitempty"`

	// Examples Examples is the directory holding the project's examples. If not
	// specified, it defaults to `examples/`.
	Examples *string `json:"examples,omitempty"`

	// Functions Functions is the directory holding the project's functions. If not
	// specified, it defaults to `functions/`.
	Functions *string `json:"functions,omitempty"`

	// Tests Tests is the directory holding the project's tests. If not
	// specified, it defaults to `tests/`.
	Tests *string `json:"tests,omitempty"`
}

// ProjectSpec ProjectSpec is the spec for a Project. Since a Project is not a Kubernetes
// resource there is no Status, only Spec.
type ProjectSpec struct {
	// APIDependencies APIDependencies are the API dependencies for this project.
	// NOTE: This is an experimental feature and is subject to change.
	APIDependencies *[]ProjectSpecAPIDependenciesItem `json:"apiDependencies,omitempty"`
	Architectures   *[]string                         `json:"architectures,omitempty"`

	// Crossplane CrossplaneConstraints specifies a packages compatibility with Crossplane versions.
	Crossplane  *ProjectSpecCrossplane        `json:"crossplane,omitempty"`
	DependsOn   *[]ProjectSpecDependsOnItem   `json:"dependsOn,omitempty"`
	Description *string                       `json:"description,omitempty"`
	ImageConfig *[]ProjectSpecImageConfigItem `json:"imageConfig,omitempty"`
	License     *string                       `json:"license,omitempty"`
	Maintainer  *string                       `json:"maintainer,omitempty"`

	// Paths ProjectPaths configures the locations of various parts of the project, for
	// use at build time.
	Paths      *ProjectSpecPaths `json:"paths,omitempty"`
	Readme     *string           `json:"readme,omitempty"`
	Repository *string           `json:"repository,omitempty"`
	Source     *string           `json:"source,omitempty"`
}

// Project Project defines an Upbound Project, which can be built into a Crossplane
// Configuration.
type Project struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ProjectAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ProjectKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec ProjectSpec is the spec for a Project. Since a Project is not a Kubernetes
	// resource there is no Status, only Spec.
	Spec *ProjectSpec `json:"spec,omitempty"`
}

// IoUpboundDevMetaV1Alpha1ProjectList ProjectList is a list of Project
type IoUpboundDevMetaV1Alpha1ProjectList = ProjectList

// ProjectList ProjectList is a list of Project
type ProjectList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of projects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundDevMetaV1Alpha1Project `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
