# generated by datamodel-codegen:
#   filename:  workdir/platform_example_com_v1alpha1_webapp.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: Dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: Dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: Optional[str] = None


class Crossplane(BaseModel):
    compositionRef: Optional[CompositionRef] = None
    compositionRevisionRef: Optional[CompositionRevisionRef] = None
    compositionRevisionSelector: Optional[CompositionRevisionSelector] = None
    compositionSelector: Optional[CompositionSelector] = None
    compositionUpdatePolicy: Optional[Literal['Automatic', 'Manual']] = None
    resourceRefs: Optional[List[ResourceRef]] = None


class Spec(BaseModel):
    crossplane: Optional[Crossplane] = None
    """
    Configures how Crossplane will reconcile this composite resource
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    message: Optional[str] = None
    observedGeneration: Optional[int] = None
    reason: str
    status: str
    type: str


class ConnectionDetails(BaseModel):
    lastPublishedTime: Optional[datetime] = None


class CrossplaneModel(BaseModel):
    connectionDetails: Optional[ConnectionDetails] = None


class Status(BaseModel):
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    crossplane: Optional[CrossplaneModel] = None
    """
    Indicates how Crossplane is reconciling this composite resource
    """


class WebApp(BaseModel):
    apiVersion: Optional[Literal['platform.example.com/v1alpha1']] = (
        'platform.example.com/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['WebApp']] = 'WebApp'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    WebAppSpec defines the desired state of WebApp.
    """
    status: Optional[Status] = None
    """
    WebAppStatus defines the observed state of WebApp.
    """


class WebAppList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[WebApp]
    """
    List of webapps. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """