# generated by datamodel-codegen:
#   filename:  workdir/meta_dev_upbound_io_v1alpha1_compositiontest.yaml

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, conint

from .....k8s.apimachinery.pkg.apis.meta import v1


class Spec(BaseModel):
    assertResources: Optional[List[Dict[str, Any]]] = None
    """
    AssertResources defines assertions to validate resources after test completion.
    Optional.
    """
    composition: Optional[Dict[str, Any]] = None
    """
    Composition specifies the composition definition inline.
    Optional.
    """
    compositionPath: Optional[str] = None
    """
    Composition specifies the composition definition path.
    Optional.
    """
    context: Optional[Dict[str, Dict[str, Any]]] = None
    """
    Context specifies context for the Function Pipeline inline as key-value pairs.
    Keys are context keys, values are JSON data.
    Optional.
    """
    extraResources: Optional[List[Dict[str, Any]]] = None
    """
    ExtraResources specifies additional resources inline.
    Optional.
    """
    functionCredentialsPath: Optional[str] = None
    """
    FunctionCredentialsPath specifies a path to a credentials file to be passed to tests.
    Optional.
    """
    observedResources: Optional[List[Dict[str, Any]]] = None
    """
    ObservedResources specifies additional observed resources inline.
    Optional.
    """
    timeoutSeconds: conint(ge=1)
    """
    Timeout for the test in seconds
    Required. Default is 30s.
    """
    validate_: Optional[bool] = Field(None, alias='validate')
    """
    Validate indicates whether to validate managed resources against schemas.
    Optional.
    """
    xr: Optional[Dict[str, Any]] = None
    """
    XR specifies the composite resource (XR) inline.
    Mutually exclusive with XRPath. At least one of XR or XRPath must be specified.
    """
    xrPath: Optional[str] = None
    """
    XRPath specifies the composite resource (XR) path.
    Mutually exclusive with XR. At least one of XR or XRPath must be specified.
    """
    xrd: Optional[Dict[str, Any]] = None
    """
    XRD specifies the XRD definition inline.
    Optional.
    """
    xrdPath: Optional[str] = None
    """
    XRD specifies the XRD definition path.
    Optional.
    """


class CompositionTest(BaseModel):
    apiVersion: Optional[Literal['meta.dev.upbound.io/v1alpha1']] = (
        'meta.dev.upbound.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['CompositionTest']] = 'CompositionTest'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    CompositionTestSpec defines the specification for the CompositionTest custom resource.
    """


class CompositionTestList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[CompositionTest]
    """
    List of compositiontests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """