[package]
name = "dotconfig"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dotconfig"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1.47", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
#https://github.com/rkyv/rkyv
rkyv = {version = "0.8", features = []}
tracing = '0.1'
tracing-subscriber = { version = '0.3', features = ['env-filter', 'json', 'serde_json'] }
#thiserror = "2.0.16"
#uuid = "1.18.1"
#sqlx = "0.8.6"
serde_json = "1.0.145"
#validator = "0.20.0"
#futures = "0.3.31"
#influxdb2 = "0.5"
#chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1.1"
predicates = "3"
tempfile = "3"
serial_test = "3"
indoc = "2"

[profile.release]
opt-level = "z"
codegen-units = 1
strip = true
lto = true
panic = "abort"
