[toolchain]
channel = "1.90.0"
profile = "minimal"
components = [
  "clippy",
  "rustfmt", 
  "rust-src",
  "rust-analyzer",
  "llvm-tools-preview"
]
targets = [
  "aarch64-apple-darwin",
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim", 
  "x86_64-apple-ios",
  "wasm32-unknown-unknown",
  "wasm32-wasip1",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl"
]