# generated by datamodel-codegen:
#   filename:  workdir/meta_dev_upbound_io_v1alpha1_e2etest.yaml

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, conint

from .....k8s.apimachinery.pkg.apis.meta import v1


class AutoUpgrade(BaseModel):
    channel: Optional[Literal['None', 'Patch', 'Stable', 'Rapid']] = 'Stable'
    """
    Channel defines the upgrade channels for Crossplane. We support the following channels where 'Stable' is the
    default:
    - None: disables auto-upgrades and keeps the control plane at its current version of Crossplane.
    - Patch: automatically upgrades the control plane to the latest supported patch version when it
      becomes available while keeping the minor version the same.
    - Stable: automatically upgrades the control plane to the latest supported patch release on minor
      version N-1, where N is the latest supported minor version.
    - Rapid: automatically upgrades the cluster to the latest supported patch release on the latest
      supported minor version.
    """


class Crossplane(BaseModel):
    autoUpgrade: Optional[AutoUpgrade] = Field(
        default_factory=lambda: AutoUpgrade.model_validate({'channel': 'Stable'})
    )
    """
    AutoUpgrades defines the auto upgrade configuration for Crossplane.
    """
    state: Optional[Literal['Running', 'Paused']] = 'Running'
    """
    State defines the state for crossplane and provider workloads. We support
    the following states where 'Running' is the default:
    - Running: Starts/Scales up all crossplane and provider workloads in the ControlPlane
    - Paused: Pauses/Scales down all crossplane and provider workloads in the ControlPlane
    """
    version: Optional[str] = None
    """
    Version is the version of Universal Crossplane to install.
    """


class Spec(BaseModel):
    cleanupTimeoutSeconds: Optional[conint(ge=1)] = 600
    """
    CleanupTimeoutSeconds defines the maximum duration in seconds for cleanup
    operations after the test completes. This timeout applies to the deletion
    of test resources and any associated managed resources. If not specified,
    defaults to 600 seconds (10 minutes). Consider increasing this value for
    tests with many resources or complex deletion dependencies.
    """
    crossplane: Crossplane
    """
    Crossplane specifies the Crossplane configuration and settings required
    for this test. This includes the version of Universal Crossplane to
    install, and optional auto-upgrade settings. The configuration defined
    here will be used to set up the controlplane before applying the test
    manifests.
    """
    defaultConditions: Optional[List[str]] = Field(None, min_length=1)
    """
    DefaultConditions specifies the expected conditions that should be met
    after the manifests are applied. These are validation checks that verify
    the resources are functioning correctly. Each condition is a string
    expression that will be evaluated against the deployed resources. Common
    conditions include checking resource status for readiness
    """
    extraResources: Optional[List[Dict[str, Any]]] = None
    """
    ExtraResources specifies additional Kubernetes resources that should be
    created or updated after the configuration has been successfully applied.
    These resources may depend on the primary configuration being in place.
    Common use cases include ConfigMaps, Secrets, providerConfigs. Each
    resource must be a valid Kubernetes object.
    """
    initResources: Optional[List[Dict[str, Any]]] = None
    """
    InitResources specifies Kubernetes resources that must be created or
    updated before the configuration is applied. These are typically
    prerequisite resources that the configuration depends on. Common use
    cases include ImageConfigs, DeploymentRuntimeConfigs, or any foundational
    resources required for the configuration to work. Each resource must be a
    valid Kubernetes object.
    """
    manifests: List[Dict[str, Any]] = Field(..., min_length=1)
    """
    Manifests contains the Kubernetes resources that will be applied as part
    of this e2e test. These are the primary resources being tested - they
    will be created in the controlplane and then validated against the
    conditions specified in DefaultConditions. Each manifest must be a valid
    Kubernetes object. At least one manifest is required. Examples include
    Claims, Composite Resources or any Kubernetes resource you want to test.
    """
    skipDelete: Optional[bool] = None
    """
    If true, skip resource deletion after test
    """
    timeoutSeconds: Optional[conint(ge=1)] = None
    """
    TimeoutSeconds defines the maximum duration in seconds that the test is
    allowed to run before being marked as failed. This includes time for
    resource creation, condition checks, and any reconciliation processes. If
    not specified, a default timeout will be used. Consider setting higher
    values for tests involving complex resources or those requiring multiple
    reconciliation cycles.
    """


class E2ETest(BaseModel):
    apiVersion: Optional[Literal['meta.dev.upbound.io/v1alpha1']] = (
        'meta.dev.upbound.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['E2ETest']] = 'E2ETest'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    E2ETestSpec defines the specification for e2e testing of Crossplane
    configurations. It orchestrates the complete test lifecycle including setting
    up controlplane, applying test resources in the correct order (InitResources
    → Configuration → ExtraResources → Manifests), validating conditions, and
    handling cleanup. This spec allows you to define e2e tests that verify your
    Crossplane compositions, providers, and managed resources work correctly
    together in a real controlplane environment.
    """


class E2ETestList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[E2ETest]
    """
    List of e2etests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """