// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/observability/internal/dagger"
	"dagger/observability/internal/querybuilder"
	"dagger/observability/internal/telemetry"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Observability) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Observability) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Observability":
		switch fnName {
		case "Apply":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var kubeconfig *dagger.File
			if inputArgs["kubeconfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeconfig"]), &kubeconfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeconfig", err))
				}
			}
			return (*Observability).Apply(&parent, ctx, source, kubeconfig)
		case "Cd":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var kubeconfig *dagger.File
			if inputArgs["kubeconfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeconfig"]), &kubeconfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeconfig", err))
				}
			}
			var dryRun bool
			if inputArgs["dryRun"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dryRun"]), &dryRun)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dryRun", err))
				}
			}
			return (*Observability).Cd(&parent, ctx, source, kubeconfig, dryRun)
		case "Ci":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).Ci(&parent, ctx, source)
		case "Delete":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var kubeconfig *dagger.File
			if inputArgs["kubeconfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeconfig"]), &kubeconfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeconfig", err))
				}
			}
			return (*Observability).Delete(&parent, ctx, source, kubeconfig)
		case "DryRun":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var kubeconfig *dagger.File
			if inputArgs["kubeconfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeconfig"]), &kubeconfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeconfig", err))
				}
			}
			return (*Observability).DryRun(&parent, ctx, source, kubeconfig)
		case "Format":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).Format(&parent, ctx, source), nil
		case "Generate":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var prometheus bool
			if inputArgs["prometheus"] != nil {
				err = json.Unmarshal([]byte(inputArgs["prometheus"]), &prometheus)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg prometheus", err))
				}
			}
			var grafana bool
			if inputArgs["grafana"] != nil {
				err = json.Unmarshal([]byte(inputArgs["grafana"]), &grafana)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg grafana", err))
				}
			}
			var jaeger bool
			if inputArgs["jaeger"] != nil {
				err = json.Unmarshal([]byte(inputArgs["jaeger"]), &jaeger)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg jaeger", err))
				}
			}
			var otel bool
			if inputArgs["otel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["otel"]), &otel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg otel", err))
				}
			}
			var loki bool
			if inputArgs["loki"] != nil {
				err = json.Unmarshal([]byte(inputArgs["loki"]), &loki)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg loki", err))
				}
			}
			var keda bool
			if inputArgs["keda"] != nil {
				err = json.Unmarshal([]byte(inputArgs["keda"]), &keda)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg keda", err))
				}
			}
			var fluxcd bool
			if inputArgs["fluxcd"] != nil {
				err = json.Unmarshal([]byte(inputArgs["fluxcd"]), &fluxcd)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg fluxcd", err))
				}
			}
			var dapr bool
			if inputArgs["dapr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dapr"]), &dapr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dapr", err))
				}
			}
			return (*Observability).Generate(&parent, ctx, source, prometheus, grafana, jaeger, otel, loki, keda, fluxcd, dapr)
		case "GenerateFile":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var output string
			if inputArgs["output"] != nil {
				err = json.Unmarshal([]byte(inputArgs["output"]), &output)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg output", err))
				}
			}
			return (*Observability).GenerateFile(&parent, ctx, source, output), nil
		case "GenerateObservability":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).GenerateObservability(&parent, ctx, source)
		case "GeneratePlatform":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).GeneratePlatform(&parent, ctx, source)
		case "Info":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Observability).Info(&parent, ctx)
		case "KclContainer":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Observability).KclContainer(&parent), nil
		case "KubectlContainer":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var kubeconfig *dagger.File
			if inputArgs["kubeconfig"] != nil {
				err = json.Unmarshal([]byte(inputArgs["kubeconfig"]), &kubeconfig)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg kubeconfig", err))
				}
			}
			return (*Observability).KubectlContainer(&parent, kubeconfig), nil
		case "Lint":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).Lint(&parent, ctx, source)
		case "Test":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).Test(&parent, ctx, source)
		case "Validate":
			var parent Observability
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Observability).Validate(&parent, ctx, source)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
