# generated by datamodel-codegen:
#   filename:  workdir/meta_dev_upbound_io_v2alpha1_project.yaml

from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel

from .....k8s.apimachinery.pkg.apis.meta import v1


class Git(BaseModel):
    path: Optional[str] = None
    """
    Path is the path within the repository to the API definition.
    """
    ref: Optional[str] = None
    """
    Ref is the git reference (branch, tag, or commit SHA).
    """
    repository: str
    """
    Repository is the git repository URL.
    """


class Http(BaseModel):
    url: str
    """
    URL is the HTTP/HTTPS URL to fetch the API dependency from.
    """


class K8s(BaseModel):
    version: str
    """
    Version is the Kubernetes API version (e.g., "v1.33.0").
    """


class ApiDependency(BaseModel):
    git: Optional[Git] = None
    """
    Git defines the git repository source for the API dependency.
    """
    http: Optional[Http] = None
    """
    HTTP defines the HTTP source for the API dependency.
    """
    k8s: Optional[K8s] = None
    """
    K8s defines the Kubernetes API version for the dependency.
    """
    type: Literal['k8s', 'crd']
    """
    Type defines the type of API dependency.
    """


class Crossplane(BaseModel):
    version: str
    """
    Semantic version constraints of Crossplane that package is compatible with.
    """


class DependsOnItem(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion of the dependency.
    """
    configuration: Optional[str] = None
    """
    Configuration is the name of a Configuration package image.
    Must be a fully qualified image name, including the registry,
    Deprecated: Specify an apiVersion, kind, and package instead.
    """
    function: Optional[str] = None
    """
    Function is the name of a Function package image.
    Must be a fully qualified image name, including the registry,
    Deprecated: Specify an apiVersion, kind, and package instead.
    """
    kind: Optional[str] = None
    """
    Kind of the dependency.
    """
    package: Optional[str] = None
    """
    Package OCI reference of the dependency. Only used when apiVersion and
    kind are set.
    Must be a fully qualified image name, including the registry,
    repository, and tag. For example, "registry.example.com/repo/package:tag".
    """
    provider: Optional[str] = None
    """
    Provider is the name of a Provider package image.
    Must be a fully qualified image name, including the registry,
    Deprecated: Specify an apiVersion and kind instead.
    """
    version: str
    """
    Version is the semantic version constraints of the dependency image.
    """


class MatchImage(BaseModel):
    prefix: str
    """
    Prefix is the prefix that should be matched.
    """
    type: Optional[Literal['Prefix']] = 'Prefix'
    """
    Type is the type of match.
    """


class RewriteImage(BaseModel):
    prefix: str
    """
    Prefix is the prefix to use when rewriting the image.
    """


class ImageConfigItem(BaseModel):
    matchImages: List[MatchImage]
    """
    MatchImages is a list of image matching rules that should be satisfied.
    """
    rewriteImage: RewriteImage
    """
    RewriteImage defines how a matched image should be rewritten.
    """


class Paths(BaseModel):
    apis: Optional[str] = None
    """
    APIs is the directory holding the project's apis. If not
    specified, it defaults to `apis/`.
    """
    examples: Optional[str] = None
    """
    Examples is the directory holding the project's examples. If not
    specified, it defaults to `examples/`.
    """
    functions: Optional[str] = None
    """
    Functions is the directory holding the project's functions. If not
    specified, it defaults to `functions/`.
    """
    operations: Optional[str] = None
    """
    Operations is the directory holding the project's operations. If not
    specified, it defaults to `operations/`.
    """
    tests: Optional[str] = None
    """
    Tests is the directory holding the project's tests. If not
    specified, it defaults to `tests/`.
    """


class Spec(BaseModel):
    apiDependencies: Optional[List[ApiDependency]] = None
    """
    APIDependencies are the API dependencies for this project.
    NOTE: This is an experimental feature and is subject to change.
    """
    architectures: Optional[List[str]] = None
    crossplane: Optional[Crossplane] = None
    """
    CrossplaneConstraints specifies a packages compatibility with Crossplane versions.
    """
    dependsOn: Optional[List[DependsOnItem]] = None
    description: Optional[str] = None
    imageConfig: Optional[List[ImageConfigItem]] = None
    license: Optional[str] = None
    maintainer: Optional[str] = None
    paths: Optional[Paths] = None
    """
    ProjectPaths configures the locations of various parts of the project, for
    use at build time.
    """
    readme: Optional[str] = None
    repository: str
    source: Optional[str] = None


class Project(BaseModel):
    apiVersion: Optional[Literal['meta.dev.upbound.io/v2alpha1']] = (
        'meta.dev.upbound.io/v2alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['Project']] = 'Project'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Optional[Spec] = None
    """
    ProjectSpec is the spec for a Project. Since a Project is not a Kubernetes
    resource there is no Status, only Spec.
    """


class ProjectList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[Project]
    """
    List of projects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """