# generated by datamodel-codegen:
#   filename:  workdir/meta_dev_upbound_io_v1alpha1_operationtest.yaml

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, conint

from .....k8s.apimachinery.pkg.apis.meta import v1


class Spec(BaseModel):
    assertResources: Optional[List[Dict[str, Any]]] = None
    """
    AssertResources defines assertions to validate resources after test completion.
    Optional.
    """
    context: Optional[Dict[str, Dict[str, Any]]] = None
    """
    Context specifies context for the Function Pipeline inline as key-value pairs.
    Keys are context keys, values are JSON data.
    Optional.
    """
    functionCredentialsPath: Optional[str] = None
    """
    FunctionCredentialsPath specifies a path to a credentials file to be passed to tests.
    Optional.
    """
    operation: Optional[Dict[str, Any]] = None
    """
    Operation specifies the Operation definition inline.
    Optional.
    """
    operationPath: Optional[str] = None
    """
    OperationPath specifies the XRD definition path.
    Optional.
    """
    requiredResources: Optional[List[Dict[str, Any]]] = None
    """
    RequiredResources specifies additional required resources inline.
    Optional.
    """
    requiredResourcesPath: Optional[str] = None
    """
    RequiredResourcesPath specifies a path to required resources file.
    Optional.
    """
    timeoutSeconds: conint(ge=1)
    """
    Timeout for the test in seconds
    Required. Default is 30s.
    """


class OperationTest(BaseModel):
    apiVersion: Optional[Literal['meta.dev.upbound.io/v1alpha1']] = (
        'meta.dev.upbound.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['OperationTest']] = 'OperationTest'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    OperationTestSpec defines the specification for the OperationTest custom resource.
    """


class OperationTestList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[OperationTest]
    """
    List of operationtests. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """