apiVersion: v1
kind: Secret
metadata:
  name: flagsmith-secret
  namespace: default
type: Opaque
stringData:
  env-key: "local-env-key"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dotconfig-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "dotconfig.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dotconfig-vs
  namespace: default
spec:
  hosts:
  - "dotconfig.local"
  gateways:
  - dotconfig-gateway
  http:
  - route:
    - destination:
        host: dotconfig
        port:
          number: 8080
    timeout: 3s
    retries:
      attempts: 3
      retryOn: 5xx,connect-failure,refused-stream
