apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dotconfig-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotconfig
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 300
  pollingInterval: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      threshold: "100"
      query: rate(http_requests_total{deployment="dotconfig"}[1m])
  - type: nats
    metadata:
      natsServerMonitoringEndpoint: "nats://data.nats.svc.cluster.local:8222"
      subject: "dotconfig.events"
      lagThreshold: "5"
