use anyhow::{Context, Result};
use chrono::Utc;
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

mod providers;

use providers::{azure, PricingProvider};

#[cfg(feature = "gcp")]
use providers::gcp;

#[cfg(feature = "aws")]
use providers::aws;

#[derive(Parser)]
#[command(name = "pricing-fetcher")]
#[command(about = "Fetches real-time cloud pricing for cost-aware provisioning")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Fetch all pricing data
    Fetch {
        /// Output format: kcl, json, yaml
        #[arg(short, long, default_value = "kcl")]
        format: String,

        /// Region to fetch pricing for
        #[arg(short, long, default_value = "us-central1")]
        region: String,

        /// Output file (stdout if not specified)
        #[arg(short, long)]
        output: Option<String>,
    },
    /// Fetch specific resource type pricing
    FetchResource {
        /// Resource type: database, registry, storage
        #[arg(short = 't', long)]
        resource_type: String,

        /// Region
        #[arg(short, long, default_value = "us-central1")]
        region: String,

        /// Output format
        #[arg(short, long, default_value = "json")]
        format: String,
    },
    /// Update Kubernetes ConfigMap with pricing data
    #[cfg(feature = "kubernetes")]
    UpdateConfigMap {
        /// ConfigMap name
        #[arg(short, long, default_value = "pricing-config")]
        name: String,

        /// Namespace
        #[arg(short = 's', long, default_value = "platform-system")]
        namespace: String,

        /// Region
        #[arg(short, long, default_value = "us-central1")]
        region: String,
    },
}

// ============================================================================
// Pricing Data Structures (matching KCL schemas)
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PricingMetadata {
    pub source: String,
    pub last_updated: String,
    pub region: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistryPricing {
    pub storage_per_gb_month: f64,
    pub egress_per_gb: f64,
    pub pull_per_1000: f64,
    pub vulnerability_scan_per_image: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatabasePricing {
    pub cpu_per_hour: f64,
    pub memory_per_gb_hour: f64,
    pub storage_per_gb_month: f64,
    pub iops_per_1000_hour: f64,
    pub backup_per_gb_month: f64,
    pub ha_multiplier: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoragePricing {
    pub storage_per_gb_month: f64,
    pub egress_per_gb: f64,
    pub operations_per_10k: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PricingConfig {
    pub metadata: PricingMetadata,
    pub registry: HashMap<String, RegistryPricing>,
    pub database: HashMap<String, DatabasePricing>,
    pub storage: HashMap<String, StoragePricing>,
}

impl PricingConfig {
    pub fn new(region: &str) -> Self {
        Self {
            metadata: PricingMetadata {
                source: "api".to_string(),
                last_updated: Utc::now().format("%Y-%m-%d").to_string(),
                region: region.to_string(),
            },
            registry: HashMap::new(),
            database: HashMap::new(),
            storage: HashMap::new(),
        }
    }

    /// Generate KCL configuration file content
    pub fn to_kcl(&self) -> String {
        let mut output = String::new();

        output.push_str("# Pricing Configuration\n");
        output.push_str("# Auto-generated by pricing-fetcher\n");
        output.push_str(&format!("# Last updated: {}\n\n", self.metadata.last_updated));

        // Schemas
        output.push_str(
            r#"schema PricingSource:
    source: str = "api"
    last_updated: str = ""
    region: str = "us-central1"

schema RegistryPricing:
    storage_per_gb_month: float
    egress_per_gb: float
    pull_per_1000: float = 0.0
    vulnerability_scan_per_image: float = 0.0

schema DatabasePricing:
    cpu_per_hour: float
    memory_per_gb_hour: float
    storage_per_gb_month: float
    iops_per_1000_hour: float = 0.0
    backup_per_gb_month: float = 0.0
    ha_multiplier: float = 2.0

schema StoragePricing:
    storage_per_gb_month: float
    egress_per_gb: float
    operations_per_10k: float = 0.0

schema PricingConfig:
    metadata: PricingSource
    registry: {str: RegistryPricing}
    database: {str: DatabasePricing}
    storage: {str: StoragePricing}

"#,
        );

        // PRICING instance
        output.push_str("PRICING = PricingConfig {\n");
        output.push_str("    metadata = PricingSource {\n");
        output.push_str(&format!("        source = \"{}\"\n", self.metadata.source));
        output.push_str(&format!(
            "        last_updated = \"{}\"\n",
            self.metadata.last_updated
        ));
        output.push_str(&format!("        region = \"{}\"\n", self.metadata.region));
        output.push_str("    }\n\n");

        // Registry pricing
        output.push_str("    registry = {\n");
        for (name, pricing) in &self.registry {
            output.push_str(&format!("        {} = RegistryPricing {{\n", name));
            output.push_str(&format!(
                "            storage_per_gb_month = {:.4}\n",
                pricing.storage_per_gb_month
            ));
            output.push_str(&format!(
                "            egress_per_gb = {:.4}\n",
                pricing.egress_per_gb
            ));
            output.push_str(&format!(
                "            vulnerability_scan_per_image = {:.4}\n",
                pricing.vulnerability_scan_per_image
            ));
            output.push_str("        }\n");
        }
        output.push_str("    }\n\n");

        // Database pricing
        output.push_str("    database = {\n");
        for (name, pricing) in &self.database {
            output.push_str(&format!("        {} = DatabasePricing {{\n", name));
            output.push_str(&format!(
                "            cpu_per_hour = {:.4}\n",
                pricing.cpu_per_hour
            ));
            output.push_str(&format!(
                "            memory_per_gb_hour = {:.4}\n",
                pricing.memory_per_gb_hour
            ));
            output.push_str(&format!(
                "            storage_per_gb_month = {:.4}\n",
                pricing.storage_per_gb_month
            ));
            output.push_str(&format!(
                "            iops_per_1000_hour = {:.4}\n",
                pricing.iops_per_1000_hour
            ));
            output.push_str(&format!(
                "            backup_per_gb_month = {:.4}\n",
                pricing.backup_per_gb_month
            ));
            output.push_str(&format!(
                "            ha_multiplier = {:.1}\n",
                pricing.ha_multiplier
            ));
            output.push_str("        }\n");
        }
        output.push_str("    }\n\n");

        // Storage pricing
        output.push_str("    storage = {\n");
        for (name, pricing) in &self.storage {
            output.push_str(&format!("        {} = StoragePricing {{\n", name));
            output.push_str(&format!(
                "            storage_per_gb_month = {:.4}\n",
                pricing.storage_per_gb_month
            ));
            output.push_str(&format!(
                "            egress_per_gb = {:.4}\n",
                pricing.egress_per_gb
            ));
            output.push_str(&format!(
                "            operations_per_10k = {:.4}\n",
                pricing.operations_per_10k
            ));
            output.push_str("        }\n");
        }
        output.push_str("    }\n");

        output.push_str("}\n");

        output
    }
}

// ============================================================================
// Main
// ============================================================================

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Fetch {
            format,
            region,
            output,
        } => {
            let config = fetch_all_pricing(&region).await?;

            let content = match format.as_str() {
                "kcl" => config.to_kcl(),
                "json" => serde_json::to_string_pretty(&config)?,
                "yaml" => serde_json::to_string_pretty(&config)?, // TODO: Add yaml support
                _ => anyhow::bail!("Unknown format: {}", format),
            };

            if let Some(path) = output {
                std::fs::write(&path, &content)
                    .with_context(|| format!("Failed to write to {}", path))?;
                println!("Pricing data written to {}", path);
            } else {
                println!("{}", content);
            }
        }
        Commands::FetchResource {
            resource_type,
            region,
            format,
        } => {
            let config = fetch_all_pricing(&region).await?;

            let data: serde_json::Value = match resource_type.as_str() {
                "database" => serde_json::to_value(&config.database)?,
                "registry" => serde_json::to_value(&config.registry)?,
                "storage" => serde_json::to_value(&config.storage)?,
                _ => anyhow::bail!("Unknown resource type: {}", resource_type),
            };

            let content = match format.as_str() {
                "json" => serde_json::to_string_pretty(&data)?,
                _ => serde_json::to_string_pretty(&data)?,
            };

            println!("{}", content);
        }
        #[cfg(feature = "kubernetes")]
        Commands::UpdateConfigMap {
            name,
            namespace,
            region,
        } => {
            update_configmap(&name, &namespace, &region).await?;
        }
    }

    Ok(())
}

async fn fetch_all_pricing(region: &str) -> Result<PricingConfig> {
    let mut config = PricingConfig::new(region);

    // Fetch from each provider
    println!("Fetching pricing data...");

    // GCP
    #[cfg(feature = "gcp")]
    {
        println!("  - Fetching GCP pricing...");
        if let Ok(pricing) = gcp::fetch_pricing(region).await {
            config.registry.insert("gcp".to_string(), pricing.registry);
            config
                .database
                .insert("cloudsql".to_string(), pricing.database);
            config.storage.insert("gcs".to_string(), pricing.storage);
        } else {
            println!("    (using defaults for GCP)");
            add_gcp_defaults(&mut config);
        }
    }
    #[cfg(not(feature = "gcp"))]
    add_gcp_defaults(&mut config);

    // AWS
    #[cfg(feature = "aws")]
    {
        println!("  - Fetching AWS pricing...");
        if let Ok(pricing) = aws::fetch_pricing(region).await {
            config.registry.insert("aws".to_string(), pricing.registry);
            config.database.insert("rds".to_string(), pricing.database);
            config.storage.insert("s3".to_string(), pricing.storage);
        } else {
            println!("    (using defaults for AWS)");
            add_aws_defaults(&mut config);
        }
    }
    #[cfg(not(feature = "aws"))]
    add_aws_defaults(&mut config);

    // Azure
    println!("  - Fetching Azure pricing...");
    if let Ok(pricing) = azure::fetch_pricing(region).await {
        config
            .registry
            .insert("azure".to_string(), pricing.registry);
        config
            .database
            .insert("azure_sql".to_string(), pricing.database);
        config
            .storage
            .insert("azure_blob".to_string(), pricing.storage);
    } else {
        println!("    (using defaults for Azure)");
        add_azure_defaults(&mut config);
    }

    // Self-hosted options (always use estimates)
    add_self_hosted_defaults(&mut config);

    config.metadata.source = "api".to_string();

    Ok(config)
}

// Default pricing data (fallback when API fails)
fn add_gcp_defaults(config: &mut PricingConfig) {
    config.registry.insert(
        "gcp".to_string(),
        RegistryPricing {
            storage_per_gb_month: 0.10,
            egress_per_gb: 0.12,
            pull_per_1000: 0.0,
            vulnerability_scan_per_image: 0.26,
        },
    );
    config.database.insert(
        "cloudsql".to_string(),
        DatabasePricing {
            cpu_per_hour: 0.0413,
            memory_per_gb_hour: 0.007,
            storage_per_gb_month: 0.17,
            iops_per_1000_hour: 0.0,
            backup_per_gb_month: 0.08,
            ha_multiplier: 2.0,
        },
    );
    config.storage.insert(
        "gcs".to_string(),
        StoragePricing {
            storage_per_gb_month: 0.020,
            egress_per_gb: 0.12,
            operations_per_10k: 0.05,
        },
    );
}

fn add_aws_defaults(config: &mut PricingConfig) {
    config.registry.insert(
        "aws".to_string(),
        RegistryPricing {
            storage_per_gb_month: 0.10,
            egress_per_gb: 0.09,
            pull_per_1000: 0.0,
            vulnerability_scan_per_image: 0.09,
        },
    );
    config.database.insert(
        "rds".to_string(),
        DatabasePricing {
            cpu_per_hour: 0.04,
            memory_per_gb_hour: 0.008,
            storage_per_gb_month: 0.115,
            iops_per_1000_hour: 0.10,
            backup_per_gb_month: 0.095,
            ha_multiplier: 2.0,
        },
    );
    config.storage.insert(
        "s3".to_string(),
        StoragePricing {
            storage_per_gb_month: 0.023,
            egress_per_gb: 0.09,
            operations_per_10k: 0.05,
        },
    );
}

fn add_azure_defaults(config: &mut PricingConfig) {
    config.registry.insert(
        "azure".to_string(),
        RegistryPricing {
            storage_per_gb_month: 0.167,
            egress_per_gb: 0.087,
            pull_per_1000: 0.0,
            vulnerability_scan_per_image: 0.0,
        },
    );
    config.database.insert(
        "azure_sql".to_string(),
        DatabasePricing {
            cpu_per_hour: 0.045,
            memory_per_gb_hour: 0.0075,
            storage_per_gb_month: 0.115,
            iops_per_1000_hour: 0.0,
            backup_per_gb_month: 0.095,
            ha_multiplier: 1.5,
        },
    );
    config.storage.insert(
        "azure_blob".to_string(),
        StoragePricing {
            storage_per_gb_month: 0.018,
            egress_per_gb: 0.087,
            operations_per_10k: 0.05,
        },
    );
}

fn add_self_hosted_defaults(config: &mut PricingConfig) {
    // Harbor (self-hosted registry)
    config.registry.insert(
        "harbor".to_string(),
        RegistryPricing {
            storage_per_gb_month: 0.023, // PVC cost
            egress_per_gb: 0.0,          // Internal
            pull_per_1000: 0.0,
            vulnerability_scan_per_image: 0.0, // Trivy is free
        },
    );

    // CloudNativePG (in-cluster Postgres)
    config.database.insert(
        "cnpg".to_string(),
        DatabasePricing {
            cpu_per_hour: 0.01,
            memory_per_gb_hour: 0.002,
            storage_per_gb_month: 0.04,
            iops_per_1000_hour: 0.0,
            backup_per_gb_month: 0.023,
            ha_multiplier: 3.0,
        },
    );

    // Neon (serverless Postgres)
    config.database.insert(
        "neon".to_string(),
        DatabasePricing {
            cpu_per_hour: 0.016,
            memory_per_gb_hour: 0.0,
            storage_per_gb_month: 0.118,
            iops_per_1000_hour: 0.0,
            backup_per_gb_month: 0.0,
            ha_multiplier: 1.0,
        },
    );

    // MinIO (self-hosted S3-compatible)
    config.storage.insert(
        "minio".to_string(),
        StoragePricing {
            storage_per_gb_month: 0.01,
            egress_per_gb: 0.0,
            operations_per_10k: 0.0,
        },
    );
}

#[cfg(feature = "kubernetes")]
async fn update_configmap(name: &str, namespace: &str, region: &str) -> Result<()> {
    use k8s_openapi::api::core::v1::ConfigMap;
    use kube::{api::PostParams, Api, Client};

    let config = fetch_all_pricing(region).await?;
    let kcl_content = config.to_kcl();

    let client = Client::try_default().await?;
    let cms: Api<ConfigMap> = Api::namespaced(client, namespace);

    let cm = ConfigMap {
        metadata: k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta {
            name: Some(name.to_string()),
            namespace: Some(namespace.to_string()),
            ..Default::default()
        },
        data: Some(
            [("pricing_config.k".to_string(), kcl_content)]
                .into_iter()
                .collect(),
        ),
        ..Default::default()
    };

    cms.create(&PostParams::default(), &cm).await?;
    println!("ConfigMap {}/{} created/updated", namespace, name);

    Ok(())
}
