apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-latency
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: dotconfig
  configName: dotconfig-io-chaos
  latency:
    latency: "200ms"
    jitter: "50ms"
  duration: "30s"
  scheduler:
    cron: "@every 5m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-fault-write
  namespace: default
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: dotconfig
  configName: dotconfig-io-chaos
  fault:
    errno: 5
  methods:
    - write
  pathSelector:
    paths:
      - "/var/log"
  duration: "10s"
  scheduler:
    cron: "@every 15m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-fault-read
  namespace: default
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: dotconfig
  configName: dotconfig-io-chaos
  fault:
    errno: 5
  methods:
    - read
  pathSelector:
    paths:
      - "/app/config"
  duration: "10s"
  scheduler:
    cron: "@every 15m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-limit
  namespace: default
spec:
  action: limit
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: dotconfig
  configName: dotconfig-io-chaos
  limit:
    rate: "5MB/s"
  pathSelector:
    paths:
      - "/tmp"
  duration: "1m"
  scheduler:
    cron: "@every 10m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-override
  namespace: default
spec:
  action: override
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: dotconfig
  configName: dotconfig-io-chaos
  override:
    source: "original"
    path: "/tmp"
    dest: "/tmp/chaos"
  duration: "20s"
  scheduler:
    cron: "@every 20m"
