# Litmus ChaosHub Generic Experiments
# These are the most common chaos experiments from Litmus ChaosHub
# Install these after the operator is running

---
# Pod Delete Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-delete
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get","list"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get","list","watch"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["get","list","create"]
      - apiGroups: ["apps"]
        resources: ["deployments","statefulsets","replicasets","daemonsets"]
        verbs: ["list","get"]
      - apiGroups: ["apps"]
        resources: ["deployments/scale","statefulsets/scale"]
        verbs: ["get","update"]
      - apiGroups: [""]
        resources: ["replicationcontrollers","replicationcontrollers/scale"]
        verbs: ["list","get"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-delete
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '15'
    - name: RAMP_TIME
      value: ''
    - name: FORCE
      value: 'true'
    - name: CHAOS_INTERVAL
      value: '5'
    - name: PODS_AFFECTED_PERC
      value: ''
    - name: TARGET_CONTAINER
      value: ''
    - name: TARGET_PODS
      value: ''
    - name: DEFAULT_HEALTH_CHECK
      value: 'false'
    - name: NODE_LABEL
      value: ''
    - name: SEQUENCE
      value: 'parallel'
    labels:
      name: pod-delete
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
---
# Container Kill Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: container-kill
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name container-kill
    command:
    - /bin/bash
    env:
    - name: TARGET_CONTAINER
      value: ''
    - name: CHAOS_INTERVAL
      value: '10'
    - name: TOTAL_CHAOS_DURATION
      value: '20'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: container-kill
---
# Pod Network Loss Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-network-loss
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-network-loss
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: NETWORK_INTERFACE
      value: 'eth0'
    - name: NETWORK_PACKET_LOSS_PERCENTAGE
      value: '100'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    - name: DESTINATION_IPS
      value: ''
    - name: DESTINATION_HOSTS
      value: ''
    labels:
      name: pod-network-loss
---
# Pod Network Latency Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-network-latency
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-network-latency
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: NETWORK_INTERFACE
      value: 'eth0'
    - name: NETWORK_LATENCY
      value: '2000'
    - name: JITTER
      value: '0'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: pod-network-latency
---
# Pod CPU Hog Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-cpu-hog
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-cpu-hog
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: CPU_CORES
      value: '1'
    - name: CPU_LOAD
      value: '100'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: pod-cpu-hog
---
# Pod Memory Hog Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-memory-hog
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-memory-hog
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: MEMORY_CONSUMPTION
      value: '500'
    - name: NUMBER_OF_WORKERS
      value: '1'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: pod-memory-hog
---
# Disk Fill Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: disk-fill
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name disk-fill
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: FILL_PERCENTAGE
      value: '80'
    - name: EPHEMERAL_STORAGE_MEBIBYTES
      value: ''
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: disk-fill
---
# Pod Failure Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-failure
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/log","pods/exec"]
        verbs: ["get","list","create"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-failure
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    labels:
      name: pod-failure
---
# Pod DNS Error Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-dns-error
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-dns-error
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: TARGET_HOSTNAMES
      value: ''
    - name: MATCH_SCHEME
      value: 'exact'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: pod-dns-error
---
# Pod IO Stress Experiment
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-io-stress
  namespace: litmus
  labels:
    instance: litmus
    app.kubernetes.io/part-of: litmus
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["create","delete","get","list","patch","update", "deletecollection"]
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["create","get","list","patch","update"]
      - apiGroups: [""]
        resources: ["pods/exec","pods/log"]
        verbs: ["create","get","list"]
      - apiGroups: ["batch"]
        resources: ["jobs"]
        verbs: ["create","list","get","delete","deletecollection"]
      - apiGroups: ["litmuschaos.io"]
        resources: ["chaosengines","chaosexperiments","chaosresults"]
        verbs: ["create","list","get","patch","update","delete"]
    image: "litmuschaos/go-runner:3.10.0"
    imagePullPolicy: IfNotPresent
    args:
    - -c
    - ./experiments -name pod-io-stress
    command:
    - /bin/bash
    env:
    - name: TOTAL_CHAOS_DURATION
      value: '60'
    - name: FILESYSTEM_UTILIZATION_PERCENTAGE
      value: '10'
    - name: VOLUME_MOUNT_PATH
      value: '/tmp'
    - name: CONTAINER_RUNTIME
      value: 'containerd'
    - name: SOCKET_PATH
      value: '/run/containerd/containerd.sock'
    labels:
      name: pod-io-stress
