// Package v1alpha1 contains generated models.
//
// Code generated by github.com/upbound/up version v0.44.0 DO NOT EDIT.
package v1alpha1

import (
	metav1 "dev.upbound.io/models/io/k8s/meta/v1"
	"time"
)

// Use time to avoid unused import errors.
var (
	_ *time.Time = nil
)

// Defines values for WebAppAPIVersion.
const (
	WebAppAPIVersionplatformExampleComV1Alpha1 WebAppAPIVersion = "platform.example.com/v1alpha1"
)

// Defines values for WebAppKind.
const (
	WebAppKindWebApp WebAppKind = "WebApp"
)

// Defines values for WebAppSpecCrossplaneCompositionUpdatePolicy.
const (
	WebAppSpecCrossplaneCompositionUpdatePolicyAutomatic WebAppSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	WebAppSpecCrossplaneCompositionUpdatePolicyManual    WebAppSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// ComExamplePlatformV1Alpha1WebApp WebApp is the Schema for the WebApp API.
type ComExamplePlatformV1Alpha1WebApp = WebApp

// WebAppAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type WebAppAPIVersion string

// WebAppKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type WebAppKind string

// WebAppSpecCrossplaneCompositionRef defines model for .
type WebAppSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// WebAppSpecCrossplaneCompositionRevisionRef defines model for .
type WebAppSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// WebAppSpecCrossplaneCompositionRevisionSelector defines model for .
type WebAppSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// WebAppSpecCrossplaneCompositionSelector defines model for .
type WebAppSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// WebAppSpecCrossplaneCompositionUpdatePolicy defines model for com.example.platform.v1alpha1.WebApp.spec.crossplane.compositionUpdatePolicy.
type WebAppSpecCrossplaneCompositionUpdatePolicy string

// WebAppSpecCrossplaneResourceRefsItem defines model for .
type WebAppSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// WebAppSpecCrossplane Configures how Crossplane will reconcile this composite resource
type WebAppSpecCrossplane struct {
	CompositionRef              *WebAppSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *WebAppSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *WebAppSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *WebAppSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *WebAppSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]WebAppSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// WebAppSpec WebAppSpec defines the desired state of WebApp.
type WebAppSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *WebAppSpecCrossplane `json:"crossplane,omitempty"`
}

// WebAppStatusConditionsItem defines model for .
type WebAppStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// WebAppStatusCrossplaneConnectionDetails defines model for .
type WebAppStatusCrossplaneConnectionDetails struct {
	LastPublishedTime *time.Time `json:"lastPublishedTime,omitempty"`
}

// WebAppStatusCrossplane Indicates how Crossplane is reconciling this composite resource
type WebAppStatusCrossplane struct {
	ConnectionDetails *WebAppStatusCrossplaneConnectionDetails `json:"connectionDetails,omitempty"`
}

// WebAppStatus WebAppStatus defines the observed state of WebApp.
type WebAppStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]WebAppStatusConditionsItem `json:"conditions,omitempty"`

	// Crossplane Indicates how Crossplane is reconciling this composite resource
	Crossplane *WebAppStatusCrossplane `json:"crossplane,omitempty"`
}

// WebApp WebApp is the Schema for the WebApp API.
type WebApp struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *WebAppAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *WebAppKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec WebAppSpec defines the desired state of WebApp.
	Spec *WebAppSpec `json:"spec,omitempty"`

	// Status WebAppStatus defines the observed state of WebApp.
	Status *WebAppStatus `json:"status,omitempty"`
}

// ComExamplePlatformV1Alpha1WebAppList WebAppList is a list of WebApp
type ComExamplePlatformV1Alpha1WebAppList = WebAppList

// WebAppList WebAppList is a list of WebApp
type WebAppList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of webapps. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComExamplePlatformV1Alpha1WebApp `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
