apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: admin-controller
spec:
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/krupnik/admin-controller
  source: github.com/upbound/project-template-scratch
