apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: webapps.platform.example.com
spec:
  group: platform.example.com
  names:
    categories:
    - crossplane
    kind: WebApp
    plural: webapps
  scope: Namespaced
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: WebApp is the Schema for the WebApp API.
        properties:
          spec:
            description: WebAppSpec defines the desired state of WebApp.
            type: object
          status:
            description: WebAppStatus defines the observed state of WebApp.
            type: object
        required:
        - spec
        type: object
    served: true
